before_script:
  - eval "$(micromamba shell hook --shell=bash)"

test:
  stage: test
  only:
    - main
    - merge_requests
    - web
  script:
    - micromamba config list
    - micromamba env create -f conda_env.yml
    - micromamba activate gitlab-ci
    # install pkg
    - pip install -e . -v --no-deps
    - export OMP_NUM_THREADS=1
    - pytest tailoredcc -v --cov tailoredcc --cov-report term --cov-report xml:coverage.xml --junitxml=report.xml
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    when: always
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
      junit: report.xml

lint:
  stage: test
  only:
    - main
    - merge_requests
    - web
  script:
    - micromamba create -n lint ruff isort -c conda-forge
    - micromamba activate lint
    - isort -c tailoredcc
    - ruff tailoredcc
