name: gitlab-ci
channels:
  - conda-forge
dependencies:
  # Build
  - git
  - openssh
  - libblas =*=*mkl
  - python =3.9
  - pip
  - adcc
  # Run
  - numpy <1.24
  - scipy >=1.2
  - opt_einsum >=3.0
  # - openfermion
  # - openfermionpyscf
  # Tests
  - pytest
  - pytest-cov
  # - pip:
    # - pyscf
