name: gitlab-ci
channels:
  - conda-forge
dependencies:
  # Build
  - git
  - openssh
  - python =3.9
  - pip
  # parsec build deps
  - cxx-compiler
  - make
  - openblas
  - pybind11
  # Run
  - numpy <1.24
  - scipy >=1.2,<1.11
  - opt_einsum >=3.0
  - pyscf
  - openfermion
  - openfermionpyscf
  - jax
  - fqe
  - pathos
  # Tests
  - pytest
  - pytest-cov
  - pyinstrument
